In [2]:
#Exp no.:5 

In [3]:
#Aim: Creation of arrays using numpy 

In [4]:
# Name:Shalimar R Kathade
# Roll no:74
# Sec: C
# Subject:ET1

In [6]:
import numpy as np

In [15]:
#creating 1D array 
a1=np.array([11,22,33,44])

In [16]:
a1

array([11, 22, 33, 44])

In [25]:
#creating 2D array
a2=np.array([[15, 25, 35, 45, 55],[10, 20, 30, 40, 50]])

In [26]:
a2

array([[15, 25, 35, 45, 55],
       [10, 20, 30, 40, 50]])

In [27]:
#creating 3d array
a3=np.matrix('10,15;20,25;30,35')

In [28]:
a3

matrix([[10, 15],
        [20, 25],
        [30, 35]])

In [29]:
#create array of 30 random integers between 15 and 26
arr=np.random.randint(10,26,size=30)
print(arr)

[23 15 16 15 12 17 16 18 23 18 17 12 11 18 19 24 22 11 24 18 23 14 10 22
 20 16 22 14 25 19]
